---
name: Biz4Devs
title: Biz4Devs
email: biz4devs@gmail.com
description: >-
  Gestão e empreendedorismo por desenvolvedores para desenvolvedores.
url: https://www.biz4devs.com
baseurl:
twitter_username: biz4devs
github_username: lucasprim

# Build settings
# theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

collections:
  authors:
    output: true

# Plugin settings
# markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categoria/:name/'

paginate: 15
paginate_path: /page:num/

# Theme Settings

lazyimages: enabled
jumbotron: enabled
disqus: biz4devs
mailchimp-list: "https://biz4devs.us10.list-manage.com\
  /subscribe/post?u=c370f76f19b193b3931203b32&amp;id=662cae13b5"
include: ["_pages"]
permalink: /:title/
logo: 'assets/images/b4d-expanded-rectangle-white.png'
favicon: 'assets/images/favicon.ico'
google_analytics: 'UA-169343340-1'

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope: 
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
